version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  flight-service:
    image: flight-service
    container_name: flight-service
    restart: on-failure
    build:
      context: src
      dockerfile: FlightService/Dockerfile
    ports:
      - "8060:8060"
    depends_on:
      - postgres

  bonus-service:
    image: bonus-service
    container_name: bonus-service
    restart: on-failure
    build:
      context: src
      dockerfile: BonusService/Dockerfile
    ports:
      - "8050:8050"
    depends_on:
      - postgres

  ticket-service:
    image: ticket-service
    container_name: ticket-service
    restart: on-failure
    build:
      context: src
      dockerfile: TicketService/Dockerfile
    ports:
      - "8070:8070"
    depends_on:
      - postgres

  api-gateway:
    image: api-gateway
    container_name: api-gateway
    restart: on-failure
    build:
      context: src
      dockerfile: GatewayService/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - ticket-service
      - bonus-service
      - flight-service

volumes:
  db-data: