CREATE DATABASE tickets;
GRANT ALL PRIVILEGES ON DATABASE tickets TO program;

CREATE DATABASE flights;
GRANT ALL PRIVILEGES ON DATABASE flights TO program;

CREATE DATABASE privileges;
GRANT ALL PRIVILEGES ON DATABASE privileges TO program;

CREATE DATABASE persons;
GRANT ALL PRIVILEGES ON DATABASE persons TO program;

CREATE DATABASE statistics;
GRANT ALL PRIVILEGES ON DATABASE statistics TO program;