name: GitHub Classroom Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2
      - name: publish
        env:
          DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: |
          echo $DOCKER_USER
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker-compose up -d kafka
          docker-compose up -d zookeeper

          docker images

          docker tag confluentinc/cp-zookeeper:7.3.2 katyavarlamova/zookeeper
          docker push katyavarlamova/zookeeper

          docker tag confluentinc/cp-kafka:7.3.2 katyavarlamova/kafka
          docker push katyavarlamova/kafka

      - name: Write out the kubeconfig info
        env:
          MY_SECRET: ${{ secrets.KUBE_CONFIG }}
        run: |
          echo "$MY_SECRET" | base64 -d >> /tmp/config
          chmod 0600 /tmp/config

      - name: Instal deps
        run: curl -sSL https://hub.mcs.mail.ru/repository/client-keystone-auth/latest/linux/client-install.sh | bash

      - name: Deploy DB
        env:
          KUBECONFIG: /tmp/config
        run: |
          source ~/vk-cloud-solutions/path.bash.inc
          helm upgrade --install postgres ./kubernetes/postgres
      
      - name: Deploy API
        env:
          KUBECONFIG: /tmp/config
        run: |
          source ~/vk-cloud-solutions/path.bash.inc
          helm upgrade --install flights ./kubernetes/flights
          kubectl apply -f ./kubernetes/ingress.yaml
      - name: Add hosts to /etc/hosts
        run: |
          sudo echo "185.130.113.206 katyavarlamova.ds.com" | sudo tee -a /etc/hosts
                

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v
